# Config variables for text classification using BERT embeddings

# DATA PREPROCESSING
path_to_training: ./data/raw/training.csv
path_to_testing: ./data/raw/testing.csv
concat : True 
test_size : 0.2
drop_social_pressure: True
max_token_count : 60
drop_class: 
  - 6-SOCIAL
  - 7-PRESSURE

# MODEL TRAINING
binary_model: False
batch_size: 64
num_epochs: 5
learning_rate: 0.001
pretrained_model: distilbert-base-uncased
optimizer: AdamW
weight_decay: 0.01
output_model: ./models/saved_models/
use_pretrained : True
hidden_size: 16
embedding_size: 16
max_token_len: 60

# OUTPUT DATA 
output_training_df_path: ./data/processed/dataframes/training
output_testing_df_path: ./data/processed/dataframes/testing
roc_plot_path : ./results/figures/roc_plot.png
stats_path: ./results/stats/stats.txt

# TESTING_CONFIG
testing_data: /Users/rt853/repos/UoB/bath-persuasion-detection/data/processed/dataframes/from_doccano_chatgpt_gen.csv
testing_model_path: /Users/rt853/repos/UoB/bath-persuasion-detection/models/saved_models/distilbert_no_social_15epo.pth
output_predictions_path: ./results/predictions/predictions.txt
test_stat_path: ./results/stats/test_stats.txt