# Config variables for text classification using BERT embeddings

# DATA PREPROCESSING
path_to_training: ./data/raw/training.csv
path_to_testing: ./data/raw/testing.csv
concat : True 
test_size : 0.2
drop_social_pressure: True
max_token_count : 60
batch_size: 32

num_epochs: 10
learning_rate: 0.001
pretrained_model: bert-base-uncased
optimizer: AdamW
weight_decay: 0.01
output_model: ./models/saved_models/
use_pretrained : False
