# Config variables for text classification using BERT embeddings

# DATA PREPROCESSING
path_to_training: /Users/rt853/repos/UoB/bath-persuasion-detection/data/binary_sentence_level/2-NEGOTIATE_binary_sentence.csv
path_to_testing: 
concat : True 
task : 'binary_classification'
test_size : 0.2
max_token_len : 60
dop_columns: 
embedding_batch:
  - bert-base-uncased
  - roberta-base
  - distilbert-base-uncased
  - roberta-large
sampler_batch: 
  - False
drop_col_batch:
  - False
output_data_path: /Users/rt853/repos/UoB/bath-persuasion-detection/data/test/dataloaders/

# MODEL TRAINING
binary_model: False
batch_size: 64
num_epochs: 5
learning_rate: 0.001
pretrained_model: bert-base-uncased
optimizer: AdamW
weight_decay: 0.01
output_model: ./models/saved_models/
use_pretrained : True
hidden_size: 16
embedding_size: 16
max_token_len: 60

# OUTPUT DATA 
output_training_df_path: ./data/processed/dataframes/training
output_testing_df_path: ./data/processed/dataframes/testing
roc_plot_path : ./results/figures/roc_plot.png
stats_path: ./results/stats/stats.txt

# TESTING_CONFIG
testing_model_path: /Users/rt853/repos/UoB/bath-persuasion-detection/data/processed/dataloaders/models/bert-base-uncased_sampler_True_drop_labels_True.pth
eval_dataloader_path: /Users/rt853/repos/UoB/bath-persuasion-detection/data/processed/dataloaders/testing/test_bert-base-uncased_sampler_True_drop_labels_True.pkl
output_predictions_path: ./results/predictions/doc_test_2.txt
test_stat_path: /Users/rt853/repos/UoB/bath-persuasion-detection/results/stats/pppppp.txteval_dataloader_path